version: "3.7"

services:
  webservice:
    build: .
    container_name: ppipe-webservice
    ports: 
      - "8000:8000"
    command: "poetry run uvicorn ppipe.webservice.main:app --host 0.0.0.0 --port 8000"