version: "3.7"

services:
  webservice:
    build: .
    container_name: ppipe-webservice
    ports: 
      - "8000:8000"
    command: "uvicorn ppipe.webservice.main:app --host 0.0.0.0 --port 8000"
    depends_on: 
      - redis_server

  worker:
    build: .
    command: "celery -A ppipe.webservice.celery.tasks worker --loglevel=INFO"
    depends_on:
      - redis_server

  flower:
    image: mher/flower
    command: "flower --broker=redis://redis_server:6379 --port=5555"
    ports:
      - "5555:5555"
    depends_on:
      - redis_server

  redis_server:
    image: redis
    ports:
      - "6379:6379"
